const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const express = require('express');

async function main() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'huts-placeholder-'));
  process.env.DATABASE_FILE = path.join(dir, 'huts.sqlite');
  process.env.WAIVER_STORAGE_DIR = path.join(dir, 'waivers');
  process.env.NODE_ENV = 'test';
  const { SqliteStore } = require('../src/data/sqliteStore');
  const legacyPath = path.join(dir, 'legacy.sqlite');
  const legacy = new SqliteStore({ dbPath: legacyPath, importTsv: false });
  const oldPerson = legacy.upsertRequestor({ Email: 'legacy@example.org', Credits: 2 });
  legacy.db.exec('DROP INDEX reservation_reference_unique; ALTER TABLE requestors DROP COLUMN reservation_reference; ALTER TABLE requestors DROP COLUMN is_placeholder;');
  legacy.close();
  const migrated = new SqliteStore({ dbPath: legacyPath, importTsv: false });
  assert.equal(migrated.getRequestorById(oldPerson.Requestor_ID).Is_placeholder, false);
  assert.equal(migrated.getRequestorById(oldPerson.Requestor_ID).Credits, 2);
  migrated.close();
  const { HEADERS, parseReservations, importReservations, listReservations, removeReservation } = require('../src/data/placeholderReservations');
  const { summarizeByChoice } = require('../src/services/requestLogic');
  const { runAssignment } = require('../src/services/assignment');
  const { captureAllocation, commitAllocation, latestAllocation } = require('../src/data/allocationRepository');
  const { effectiveRequestors } = require('../src/services/placeholderPriority');
  const { runContentionAlerts } = require('../src/services/contentionAlertWorker');
  const year = new Date().getFullYear();
  const tsv = (rows) => `${HEADERS.join('\t')}\n${rows.map((r) => r.join('\t')).join('\n')}\n`;
  const booking = (ref, name = 'Board retreat', hut = 'Benson', guests = 4) => [ref, name, hut, `${year}-12-20`, '', `${year}-12-22`, guests, 'Admin private reason'];
  const store = new SqliteStore({ importTsv: false, clock: () => `${year}-10-05T12:00:00Z` });
  const admin = store.upsertRequestor({ Email: 'admin@example.org', Admin: true, Credits: 3, Lottery_value: 0.3 });
  const user = store.upsertRequestor({ Email: 'user@example.org', Credits: 1, Lottery_value: 0.2 });
  assert.equal(user.Is_placeholder, false);
  store.setApplicationMode('trip-request');
  store.replaceRequestsForRequestor(user.Requestor_ID, [{ Benson: true, Arrival: `${year}-12-20`, Departure: `${year}-12-22`, Choice_Number: 1, Spots_min: 9, Spots_ideal: 9 }]);
  store.alerts.initialize();
  assert.deepEqual(importReservations(store, tsv([booking('one')]), admin.Requestor_ID), { created: 1, updated: 0 });
  const first = listReservations(store)[0];
  const placeholder = store.getRequestorById(first.Requestor_ID, { includePrivate: true });
  assert.equal(placeholder.first_name, 'Board retreat'); assert.equal(placeholder.Is_placeholder, true);
  assert(placeholder.Email.endsWith('@PLACEHOLDER.INVALID'));
  assert.equal(store.listRequests().find((r) => r.Requestor_ID === user.Requestor_ID).contention_status, 'losing');
  assert(!store.alerts.snapshots(year).has(first.Requestor_ID));
  assert(store.alerts.snapshots(year).has(user.Requestor_ID));
  assert.deepEqual(importReservations(store, tsv([booking('one', 'Updated name')]), admin.Requestor_ID), { created: 0, updated: 1 });
  assert.equal(listReservations(store)[0].Requestor_ID, first.Requestor_ID);
  assert.equal(listReservations(store)[0].requests[0].Request_ID, first.requests[0].Request_ID);
  assert.equal(listReservations(store)[0].Name, 'Updated name');
  const unchanged = () => JSON.stringify([store.listRequestors({ includePrivate: true }), store.listRequests()]);
  const before = unchanged();
  store.db.exec("CREATE TRIGGER fail_placeholder BEFORE INSERT ON ski_trip_requests BEGIN SELECT RAISE(ABORT, 'injected booking failure'); END;");
  assert.throws(() => importReservations(store, tsv([booking('rolled-back', 'Rollback', 'Grubb')])), /injected booking failure/);
  store.db.exec('DROP TRIGGER fail_placeholder');
  assert.equal(unchanged(), before, 'failed request insertion rolls back its newly created placeholder');
  assert.throws(() => importReservations(store, tsv([booking('new', 'Conflict', 'Benson', 9)])), /capacity/);
  assert.equal(unchanged(), before);
  assert.throws(() => parseReservations(tsv([booking('dup'), booking('dup')])), /Duplicate reference/);
  assert.throws(() => parseReservations(tsv([booking('bad', '', 'Benson')])), /Name/);
  assert.throws(() => parseReservations(tsv([booking('bad', 'Invalid', 'Unknown')])), /Hut/);
  assert.throws(() => parseReservations(tsv([booking('bad', 'Invalid', 'Benson', 1.5)])), /integer/);
  assert.throws(() => parseReservations('x'.repeat(2 * 1024 * 1024 + 1)), /2 MB/);
  const traverse = booking('traverse', 'Ski patrol', 'Benson->Bradley', 2); traverse[4] = `${year}-12-21`;
  importReservations(store, tsv([traverse]), admin.Requestor_ID);
  const legs = listReservations(store).find((b) => b.Reservation_reference === 'traverse').requests;
  assert.equal(legs.length, 2); assert.equal(legs[0].Combination_first_request, legs[1].Combination_first_request);
  assert.throws(() => parseReservations(tsv([booking('bad-traverse', 'Bad', 'Benson->Bradley')])), /traverse/);
  store.updateRequestorById(user.Requestor_ID, { Credits: 100 }, { allowAdminFields: true });
  const people = new Map(store.listRequestors().map((p) => [p.Requestor_ID, p]));
  assert(effectiveRequestors(people).get(first.Requestor_ID).Credits > 100);
  assert.throws(() => effectiveRequestors(new Map([[1, { Credits: 900719925474099.1, Is_placeholder: false }], [2, { Is_placeholder: true }]])), /range|limit/);
  const summary = summarizeByChoice(store.listRequests(), 1, user.Requestor_ID, people);
  assert.equal(summary.find((c) => c.date === `${year}-12-20` && c.hut === 'Benson').existingReservationSpots, 6);
  assert(!summary.some((c) => c.date === `${year}-12-22`));
  const full = booking('full', 'Entire hut', 'Benson', 12); full[3] = `${year}-12-22`; full[5] = `${year}-12-24`;
  importReservations(store, tsv([full]), admin.Requestor_ID);
  const fullSummary = summarizeByChoice(store.listRequests(), 1, user.Requestor_ID, new Map(store.listRequestors().map((p) => [p.Requestor_ID, p])));
  assert.equal(fullSummary.find((c) => c.date === `${year}-12-22` && c.hut === 'Benson').existingReservationSpots, 12);
  removeReservation(store, 'full', admin.Requestor_ID);
  let snapshot = captureAllocation(store, year);
  const solved = await runAssignment(snapshot.requests, new Map(snapshot.requestors.map((p) => [p.Requestor_ID, p])), { regenerateLotteryNumbers: true });
  assert.equal(solved.placeholderBookings, 2); assert.equal(solved.placeholderPersonNights, 12);
  assert.equal(solved.countsByChoice.none, 1); assert.equal(solved.scores.length, 1); assert.equal(solved.policyVersion, 'credit-rank-person-nights-v3');
  assert(snapshot.requests.filter((r) => r.Requestor_ID === first.Requestor_ID).every((r) => r.Status === 'granted' && r.Spots_granted === 4));
  commitAllocation(store, snapshot, snapshot.requests, solved);
  assert.equal(latestAllocation(store).stale, false);
  const history = store.db.prepare('SELECT * FROM allocation_runs').all();
  snapshot = captureAllocation(store, year);
  const delayed = await runAssignment(snapshot.requests, new Map(snapshot.requestors.map((p) => [p.Requestor_ID, p])), { regenerateLotteryNumbers: false });
  importReservations(store, tsv([booking('one', 'Changed name', 'Benson', 3)]), admin.Requestor_ID);
  assert.throws(() => commitAllocation(store, snapshot, snapshot.requests, delayed), /inputs changed/);
  assert.equal(latestAllocation(store).stale, true);
  assert.deepEqual(store.db.prepare('SELECT * FROM allocation_runs').all(), history);
  const badRows = store.listRequests().map((r) => r.Requestor_ID === first.Requestor_ID ? { ...r, Spots_min: 12, Spots_ideal: 12 } : r);
  await assert.rejects(() => runAssignment(badRows, new Map(store.listRequestors().map((p) => [p.Requestor_ID, p]))), /capacity/);
  assert.throws(() => store.bulkUpsertRequestors([{ Email: placeholder.Email, Credits: 0 }]), /Existing reservations/);
  assert.throws(() => store.upsertRequestor({ Email: 'forged@example.org', Is_placeholder: true }), /reserved/);
  store.db.prepare('INSERT OR REPLACE INTO contention_alert_recipients(requestor_id, season, baseline, observed, pending, changed_at) VALUES (?, ?, ?, ?, ?, ?)').run(first.Requestor_ID, year, '[]', '[]', '{}', `${year}-10-05T00:00:00Z`);
  assert(!store.alerts.eligible().some((s) => s.requestor_id === first.Requestor_ID));
  const sent = [];
  store.contentionClock = () => `${year}-10-05T14:00:00Z`;
  await runContentionAlerts(store, { force: true, environment: { CONTENTION_ALERTS_ENABLED: 'true', APP_PUBLIC_URL: 'https://example.org', MAIL_TRANSPORT: 'console' }, transport: { sendMail: async (m) => { sent.push(m.to); return { accepted: [m.to] }; } } });
  assert(!sent.includes(placeholder.Email));
  assert(sent.includes(user.Email), 'real volunteers still receive reservation-induced contention alerts after the quiet period');
  store.close();
  const { apiRouter, store: apiStore } = require('../src/routes/api');
  const app = express(); app.use(express.json({ limit: '2mb' })); app.use((req, res, next) => { req.session = { userId: Number(req.headers['x-test-user']) }; next(); }); app.use('/api', apiRouter);
  const server = app.listen(0, '127.0.0.1'); await new Promise((r) => server.once('listening', r));
  const base = `http://127.0.0.1:${server.address().port}/api`;
  const headers = { 'Content-Type': 'application/json', 'x-test-user': String(admin.Requestor_ID) };
  try {
    assert.equal(listReservations(apiStore).find((b) => b.Reservation_reference === 'one').Name, 'Changed name');
    let response = await fetch(`${base}/admin/reservations`, { method: 'POST', headers, body: JSON.stringify({ tsv: tsv([booking('paste', 'Pasted booking', 'Grubb')]) }) });
    assert.equal(response.status, 200); assert.equal((await response.json()).created, 1);
    const form = new FormData(); form.append('file', new Blob([tsv([booking('paste', 'Uploaded update', 'Grubb')])]), 'reservations.tsv');
    response = await fetch(`${base}/admin/reservations`, { method: 'POST', headers: { 'x-test-user': String(admin.Requestor_ID) }, body: form });
    assert.equal(response.status, 200); assert.equal((await response.json()).updated, 1);
    assert.equal((await fetch(`${base}/admin/reservations`, { headers: { ...headers, 'x-test-user': String(user.Requestor_ID) } })).status, 403);
    assert.equal((await fetch(`${base}/me`, { headers: { ...headers, 'x-test-user': String(first.Requestor_ID) } })).status, 401);
    const authBefore = apiStore.getRequestorById(first.Requestor_ID, { includePrivate: true });
    response = await fetch(`${base}/send-email`, { method: 'POST', headers, body: JSON.stringify({ email: placeholder.Email }) });
    assert.equal(response.status, 200); assert.deepEqual(apiStore.getRequestorById(first.Requestor_ID, { includePrivate: true }), authBefore);
    const { currentAgreementVersions } = require('../src/services/agreements');
    apiStore.updateRequestorAuthFields(first.Requestor_ID, { login_code: 1234, code_generated_when: new Date().toISOString() });
    response = await fetch(`${base}/check-login`, { method: 'POST', headers, body: JSON.stringify({ email: placeholder.Email, code: 1234, agreementVersions: currentAgreementVersions() }) });
    assert.equal(response.status, 401);
    response = await fetch(`${base}/requestor/${first.Requestor_ID}/requests`, { method: 'PUT', headers, body: JSON.stringify({ requests: first.requests }) });
    assert.equal(response.status, 400);
    const rows = apiStore.volunteerManagementPayload().rows; assert(!rows.some((p) => p.Requestor_ID === first.Requestor_ID));
    const exported = await (await fetch(`${base}/admin/download/requests-joined`, { headers })).text(); assert(exported.includes('Is_placeholder')); assert(exported.includes('Reservation_reference'));
    assert(exported.includes('Changed name'));
    response = await fetch(`${base}/admin/reservations/paste`, { method: 'DELETE', headers }); assert.equal(response.status, 200);
    assert(!listReservations(apiStore).some((b) => b.Reservation_reference === 'paste'));
    removeReservation(apiStore, 'traverse', admin.Requestor_ID); assert.equal(apiStore.getRequestorById(legs[0].Requestor_ID), null);
    console.log('Placeholder reservation tests passed: names, traverses, repeat imports, atomic conflicts, priority, allocation/history, login/mail exclusion, upload/paste and removal.');
  } finally { await new Promise((r) => server.close(r)); apiStore.close(); }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
